# 1 - If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
# The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

n1 = 1000
multiples = []
(1..n1).each do |i|
  # first find all the multiples of 3 & 5, and place them in the multiples array
  multiples << i if i % 3 == 0 || i % 5 == 0
end
# then find the sum of the multiples array
return multiples.inject(:+)


# 2 - Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fib_seq = [1]
n2 = 2
# first create the fibonacci sequence
while n2 < 4000000 do
  fib_seq << n2
  n2 = fib_seq[-2] + n2
end
# then take only the even values from the sequence and add them up
even_seq = []
fib_seq.each { |i| even_seq << i if i % 2 == 0 }
return even_seq.inject(:+)

